domain: yogyakarta-temple-tours.com
brand_en: Yogyakarta Temple Tours
foreign_domains:
- ramakusuma.com
whitelist:
- Yogyakarta
- Borobudur
- Prambanan
- Jomblang
- Merapi
- Ramayana
- Java
- Sultan
- Kraton
- Malioboro
- Batik
