brand_de: Yogyakarta Tempeltouren
brand_en: Yogyakarta Temple Tours
brand_es: Tours de Templos de Yogyakarta
domain: yogyakarta-temple-tours.com
foreign_domains:
- ramakusuma.com
whitelist:
- Yogyakarta
- Borobudur
- Prambanan
- Jomblang
- Merapi
- Ramayana
- Java
- Sultan
- Kraton
- Malioboro
- Batik
