#!/bin/bash
# gates.sh — Vercel buildCommand gate script
# Auto-generated by vendor_gates.sh from gate-config.json
# DO NOT EDIT BY HAND — regenerate with: vendor_gates.sh <site_dir>
#
# Runs on Vercel build servers. Shell-only, no Python dependency.
# Uses awk + grep -E (macOS/Linux compatible).
# Exit 0 = PASS (static files served). Non-zero = BLOCKED.

SITE_DIR="${1:-.}"
FAIL=0
MIN_WORDS=400
ANTIWORDS="breathtaking|stunning|unforgettable|magical|paradise|hidden gem|incredible|amazing|spectacular|unique|world\.class|seamless|curated|immersive|life\.changing|unparalleled|elevate your|bucket\.list|nestled|boasts|renowned|once\.in\.a\.lifetime|pristine"

echo "━━━ VERCEL BUILD GATE — $(date -u +%Y-%m-%dT%H:%M:%SZ) ━━━"
echo ""

# 1. Anti-word scan (changed files only)
echo "[1/3] Anti-word scan (changed files only)..."
FOUND=0
CHANGED=$(git diff --name-only HEAD 2>/dev/null | grep '\.html$' || true)
if [ -z "$CHANGED" ]; then
    echo "  ✅ No HTML files changed"
else
    for f in $CHANGED; do
        hits=$(awk '/<script/,/<\/script>/ {next} 1' "$SITE_DIR/$f" | grep -inEw "$ANTIWORDS" | grep -v '<meta' || true)
        if [ -n "$hits" ]; then
            echo "  ❌ ANTI-WORD in $f:"
            echo "$hits" | head -5 | sed 's/^/     /'
            FOUND=1
        fi
    done
fi
if [ "$FOUND" -eq 0 ]; then
    echo "  ✅ Clean"
else
    FAIL=1
fi
echo ""

# 1b. Language audit (changed files only)
echo "[1b/4] Language audit..."
LANG_ISSUES=0
if [ -n "$CHANGED" ]; then
  for f in $CHANGED; do
    rel="$f"
    in_de=$(echo "$rel" | grep -q '^de/' && echo 1 || echo 0)
    in_es=$(echo "$rel" | grep -q '^es/' && echo 1 || echo 0)
    lang_tag=$(head -5 "$SITE_DIR/$f" 2>/dev/null | grep -o 'lang="[^"]*"' | head -1 || echo "")
    noindex=$(grep -c 'name="robots".*noindex' "$SITE_DIR/$f" 2>/dev/null || echo 0)
    if [ "$lang_tag" = 'lang="de"' ] && [ "$in_de" != "1" ] && [ "$noindex" = "0" ]; then
      echo "  ⚠️  $f: lang=de at EN path without noindex"
      LANG_ISSUES=1
    fi
    if [ "$lang_tag" = 'lang="es"' ] && [ "$in_es" != "1" ] && [ "$noindex" = "0" ]; then
      echo "  ⚠️  $f: lang=es at EN path without noindex"
      LANG_ISSUES=1
    fi
  done
fi
if [ "$LANG_ISSUES" -eq 0 ]; then
  echo "  ✅ Language tags consistent"
else
  FAIL=1
fi
echo ""

# 2. Word count floor (editorial pages)
echo "[2/4] Word counts..."
for f in $(find "$SITE_DIR" -name '*.html' -not -path '*/.git/*' -not -path '*/backup*/*' -not -path '*/.review/*' 2>/dev/null); do
    basename=$(basename "$f")
    # Skip utility pages
    case "$basename" in
        contact.html) continue ;;
                privacy.html) continue ;;
                404.html) continue ;;
                terms.html) continue ;;
    esac
    # Strip HTML tags + script blocks via awk, then count words
    words=$(awk '/<script/,/<\/script>/ {next} 1' "$f" | sed 's/<[^>]*>//g' | wc -w | tr -d ' ')
    if [ "$words" -lt "$MIN_WORDS" ]; then
        echo "  ❌ THIN: $(basename $f) — $words words (need ≥$MIN_WORDS)"
        FAIL=1
    fi
done
if ! find "$SITE_DIR" -name '*.html' -not -path '*/.git/*' -not -path '*/backup*/*' 2>/dev/null | grep -q .; then
    echo "  ❌ No HTML files found"
    FAIL=1
else
    echo "  ✅ All pages meet minimum"
fi
echo ""

# 3. Viator link count (every editorial page must have ≥1)
echo "[3/4] Viator link coverage..."
for f in $(find "$SITE_DIR" -name '*.html' -not -path '*/.git/*' -not -path '*/backup*/*' -not -path '*/.review/*' 2>/dev/null); do
    basename=$(basename "$f")
    case "$basename" in
        contact.html) continue ;;
                privacy.html) continue ;;
                404.html) continue ;;
                terms.html) continue ;;
    esac
    links=$(grep -c 'viator.com' "$f" 2>/dev/null)
    links=${links:-0}
    if [ "$links" -eq 0 ] 2>/dev/null; then
        echo "  ❌ ZERO VIATOR LINKS: $(basename $f)"
        FAIL=1
    fi
done
echo "  ✅ All pages have Viator links"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if [ "$FAIL" -eq 0 ]; then
    echo "✅ VERCEL GATE PASSED"
else
    echo "❌ VERCEL GATE FAILED — deploy blocked"
fi
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# GATE_MODE=warn → report violations but never block deploy
if [ "${GATE_MODE:-block}" = "warn" ]; then
    echo "  ℹ️  GATE_MODE=warn — reporting violations, NOT blocking deploy"
    FAIL=0
fi

exit $FAIL
