#!/bin/bash
# gates.sh — Vercel buildCommand gate script
# Auto-generated by vendor_gates.sh from gate-config.json
# DO NOT EDIT BY HAND — regenerate with: vendor_gates.sh <site_dir>
#
# Runs on Vercel build servers. Shell-only, no Python dependency.
# Uses awk + grep -E (macOS/Linux compatible).
# Exit 0 = PASS (static files served). Non-zero = BLOCKED.

SITE_DIR="${1:-.}"
FAIL=0
MIN_WORDS=400
ANTIWORDS="breathtaking|stunning|unforgettable|magical|paradise|hidden gem|incredible|amazing|spectacular|unique|world\.class|seamless|curated|immersive|life\.changing|unparalleled|elevate your|bucket\.list|nestled|boasts|renowned|once\.in\.a\.lifetime|pristine"

echo "━━━ VERCEL BUILD GATE — $(date -u +%Y-%m-%dT%H:%M:%SZ) ━━━"
echo ""

# 1. Anti-word scan (English — awk strips scripts, grep checks body with word boundaries)
echo "[1/3] Anti-word scan..."
FOUND=0
for f in $(find "$SITE_DIR" -name '*.html' -not -path '*/.git/*' -not -path '*/backup*/*' -not -path '*/.review/*' 2>/dev/null); do
    # awk removes everything between <script> and </script> inclusive (macOS compatible)
    # grep -inEw uses word boundaries to avoid partial word matches (e.g., "best" in "asbestos")
    hits=$(awk '/<script/,/<\/script>/ {next} 1' "$f" | grep -inEw "$ANTIWORDS" | grep -v '<meta' || true)
    if [ -n "$hits" ]; then
        echo "  ❌ ANTI-WORD in $(basename $f):"
        echo "$hits" | head -5 | sed 's/^/     /'
        FOUND=1
    fi
done
if [ "$FOUND" -eq 0 ]; then
    echo "  ✅ Clean"
else
    FAIL=1
fi
echo ""

# 2. Word count floor (editorial pages)
echo "[2/3] Word counts..."
for f in $(find "$SITE_DIR" -name '*.html' -not -path '*/.git/*' -not -path '*/backup*/*' -not -path '*/.review/*' 2>/dev/null); do
    basename=$(basename "$f")
    # Skip utility pages
    case "$basename" in
        contact.html) continue ;;
                privacy.html) continue ;;
                404.html) continue ;;
                terms.html) continue ;;
    esac
    # Strip HTML tags + script blocks via awk, then count words
    words=$(awk '/<script/,/<\/script>/ {next} 1' "$f" | sed 's/<[^>]*>//g' | wc -w | tr -d ' ')
    if [ "$words" -lt "$MIN_WORDS" ]; then
        echo "  ❌ THIN: $(basename $f) — $words words (need ≥$MIN_WORDS)"
        FAIL=1
    fi
done
if ! find "$SITE_DIR" -name '*.html' -not -path '*/.git/*' -not -path '*/backup*/*' 2>/dev/null | grep -q .; then
    echo "  ❌ No HTML files found"
    FAIL=1
else
    echo "  ✅ All pages meet minimum"
fi
echo ""

# 3. Viator link count (every editorial page must have ≥1)
echo "[3/3] Viator link coverage..."
for f in $(find "$SITE_DIR" -name '*.html' -not -path '*/.git/*' -not -path '*/backup*/*' -not -path '*/.review/*' 2>/dev/null); do
    basename=$(basename "$f")
    case "$basename" in
        contact.html) continue ;;
                privacy.html) continue ;;
                404.html) continue ;;
                terms.html) continue ;;
    esac
    links=$(grep -c 'viator.com' "$f" 2>/dev/null)
    links=${links:-0}
    if [ "$links" -eq 0 ] 2>/dev/null; then
        echo "  ❌ ZERO VIATOR LINKS: $(basename $f)"
        FAIL=1
    fi
done
echo "  ✅ All pages have Viator links"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if [ "$FAIL" -eq 0 ]; then
    echo "✅ VERCEL GATE PASSED"
else
    echo "❌ VERCEL GATE FAILED — deploy blocked"
fi
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

exit $FAIL
